apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations: 
    metallb.universe.tf/allow-shared-ip: lkarine 
spec:
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: grafana
    

    
    
  
    
    
  