apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
      app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-pod
        image: grafana-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
         
