apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations: 
    metallb.universe.tf/allow-shared-ip: lkarine 
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - port: 21
      targetPort: 21
      protocol: TCP
      name: ftps21
    - port: 40000
      targetPort: 40000
      protocol: TCP
      name: ftps40000
    
    
    
  